EspressoSystems/jellyfish

- CHANGELOG.md
- utilities/src/serialize.rs
A super minor modification, reported from downstream: 
```rust
// This incurs compilation error:
// the method `unwrap` exists for enum `Result<MyStruct, TaggedBlobError>`, but its trait bound were not satisfied
// the following trait bounds were not satisfied:
// `TaggedBlobError: Debug` [E0599] 
let x = MyStruct::from_str(&ser_str).unwrap();
// currently can only do something like:
let x = MyStruct::from_str(&ser_str).unwrap_or_default();
```
---
> derive `Debug` for `TaggedBlobError`

- primitives/src/schnorr_dsa.rs
I recently created a CLI utility for generating signing keys. I found that I wanted to print the private key using tagged base 64, so that it can be easily copied and pasted to RPass, for example. For this to work we need to add a `#[tagged_blob()]` annotation.
> Add serde and Display/FromStr for schnorr_dsa::KeyPair

- plonk/src/circuit/customized/ultraplonk/plonk_verifier/gadgets.rs
- plonk/src/circuit/customized/ultraplonk/plonk_verifier/poly.rs
- plonk/src/proof_system/verifier.rs
Small PR refactoring to `.ok_or_else`. Tool-aided by [comby-rust](https://github.com/huitseeker/comby-rust)
> chore: refactor exact instances of `ok_or_else`

- plonk/src/circuit/customized/ecc/msm.rs
- plonk/src/circuit/customized/ultraplonk/lookup_table.rs
- plonk/src/circuit/customized/ultraplonk/plonk_verifier/gadgets.rs
- plonk/src/circuit/customized/ultraplonk/plonk_verifier/poly.rs
- plonk/src/proof_system/verifier.rs
An important API comment: the key index of the lookup variable should be range-checked before calling `create_table_and_lookup_variable()`, otherwise one may set it outside the bounds of the array, and thus doing a lookup into one of the _other_ tables.
closes: #XXXX
---
> a comment on lookup table creation api

- plonk/src/circuit/basic.rs
- plonk/src/circuit/customized/ecc/msm.rs
- plonk/src/circuit/customized/gates.rs
- plonk/src/circuit/customized/ultraplonk/lookup_table.rs
- plonk/src/circuit/gates.rs
- plonk/src/circuit/mod.rs
- plonk/src/proof_system/prover.rs
- plonk/src/proof_system/snark.rs
- plonk/src/proof_system/structs.rs
- plonk/src/proof_system/verifier.rs
closes: #48   (and a followup of #47 )
- Add an error path test: the circuit should be unsatisfiable if the element to be looked up is in a separate table. (Thanks @tri-joe for spotting it)
- Refactor the code to use Plookup paper's original approach for supporting multiple tables.
- Removed unnecessary range-check gates in MSM.
---
> Table domain separation

- plonk/src/circuit/customized/ecc/glv.rs
- plonk/src/circuit/customized/ecc/mod.rs
- plonk/src/circuit/customized/mod.rs
- primitives/src/circuit/schnorr_dsa.rs
> update API: is_xxx to check_xxx when self is mutated

- plonk/src/circuit/basic.rs
- primitives/src/circuit/schnorr_dsa.rs
- primitives/src/errors.rs
- primitives/src/lib.rs
- primitives/src/signatures/bls.rs
- primitives/src/signatures/mod.rs
- primitives/src/signatures/schnorr.rs
- primitives/src/utils.rs
- rescue/src/errors.rs
> signature trait

- CHANGELOG.md
- primitives/Cargo.toml
- primitives/src/hash_to_group/mod.rs
- primitives/src/hash_to_group/short_weierstrass.rs
- primitives/src/hash_to_group/twisted_edward.rs
- primitives/src/hash_to_group/twisted_edwards.rs
- primitives/src/signatures/bls.rs
- primitives/src/vrf/blsvrf.rs
Implement hash to group features for twisted edwards curves
---
> impl H2G for TE curves

- CHANGELOG.md
- plonk/Cargo.toml
- plonk/src/proof_system/structs.rs
- primitives/Cargo.toml
- primitives/src/merkle_tree.rs
- primitives/src/signatures/bls.rs
- primitives/src/signatures/schnorr.rs
- utilities/Cargo.toml
- utilities/src/lib.rs
- utilities/src/serialize.rs
- utilities_derive/src/lib.rs
As discussed in zulip, we want to make sure we don't have conflicting `tagged-base64` tags. For this I've made [espresso-systems-common](https://github.com/EspressoSystems/espresso-systems-common)
The `#[tagged_blob(...)]` macro did not support constants. This PR adds this, as well as a test to make sure the new derive macro actually works.
---
> Made `tagged_blob` be able to accept constants

- plonk/src/lib.rs
- plonk/src/proof_system/structs.rs
As is required by zprice spec, the judges will replace `PlonkKzgSnark` in Line 53 with the crate implemented by the submitter:
https://github.com/EspressoSystems/jellyfish/blob/08f24d47e5ec29b977c4e8035d33dbe18c17a8d0/zprice/README.md?plain=1#L40-L55
However, the fields in `ProvingKey`, `Proof`, and some other structs are currently not visible by third-party crates, making it impossible to get the selector polynomials, construct a proof, etc. in a custom implementation of PLONK prover.
This PR makes the necessary structs and fields public to address this issue.
---
> Update: make structs and fields related to proof generation public

- CHANGELOG.md
- plonk/Cargo.toml
- primitives/Cargo.toml
- rescue/Cargo.toml
- utilities/Cargo.toml
- utilities_derive/Cargo.toml
Small version bump to get #72 released, as the `tagged_blob` macro change is needed for CAP and CAPE.
Looking at the `CHANGELOG.md`, it looks like there were several features mentioned as "pending" there but they were already released. I've marked those as `0.1.1`.
> Release 0.1.2

- CHANGELOG.md
- plonk/src/proof_system/prover.rs
- plonk/src/proof_system/snark.rs
Sync with the recent [bug fix of Plonk paper](https://twitter.com/rel_Aztec/status/1542474186664210432?s=20&t=AXa-oonIR5EimKsMyaybWA) on masking the splitting polynomials to ensure successful ZK simulator.
The slight modification in our implementation is that our splitting step degree is `n+2` instead of `n`. (since our splitting polynomials are of degree `= n+1`, see [here](https://github.com/EspressoSystems/jellyfish/blob/main/plonk/src/proof_system/prover.rs#L897) and [here](https://github.com/EspressoSystems/jellyfish/blob/main/plonk/src/proof_system/prover.rs#L897))
@chancharles92 Do you remember why we decide to do this instead of `split_lo + split_mid * X^n + ...` as in the paper?
---
checked off. …
> mask splitting polys for zk

- .github/workflows/build.yml
- plonk/benches/bench.rs
- plonk/examples/proof_of_exp.rs
- plonk/src/circuit/customized/ultraplonk/plonk_verifier/gadgets.rs
- plonk/src/circuit/customized/ultraplonk/plonk_verifier/mod.rs
- plonk/src/errors.rs
- plonk/src/proof_system/batch_arg.rs
- plonk/src/proof_system/mod.rs
- plonk/src/proof_system/prover.rs
- plonk/src/proof_system/snark.rs
- plonk/src/proof_system/structs.rs
Major changes include: 
- Remove `'a` lifetime from `CommitterKey` for kzg therefore most of other related structs by introducing conversion from `CommitterKey` to `ark_poly_commit::kzg10::Powers`
- Add back `universal_setup` and circuit-specific `preprocess` back to `trait Snark`
- Rename `trait Snark` to `trait UniversalSNARK`
closes: #78
---
> update Snark -> UniversalSNARK trait

- .github/workflows/build.yml
- plonk/Cargo.toml
- plonk/benches/bench.rs
- plonk/src/circuit/basic.rs
- plonk/src/circuit/customized/ecc/mod.rs
- plonk/src/errors.rs
- plonk/src/lib.rs
- plonk/src/par_utils.rs
- plonk/src/proof_system/prover.rs
- plonk/src/proof_system/snark.rs
- plonk/src/proof_system/structs.rs
- plonk/src/testing_apis.rs
- primitives/Cargo.toml
- primitives/src/elgamal.rs
- primitives/src/merkle_tree.rs
- primitives/src/signatures/bls.rs
- primitives/src/signatures/schnorr.rs
- rescue/Cargo.toml
- rescue/src/lib.rs
- scripts/check_no_std.sh
- utilities/Cargo.toml
- utilities/src/serialize.rs
Major changes include: 
- adjust feature flag dep of arkworks so that by default we don't use any `std` components
- remove unnecessary feature flag declaration (or `default-features = false`) on arkworks
- use `hashbrown`'s HashSet, HashMap 
- put `rayon` accelerated code to `parallel` feature flag which is on by default
closes: #84 
---
> Restoring no_std compliance

- .github/workflows/build.yml
- CHANGELOG.md
- plonk/Cargo.toml
- plonk/benches/bench.rs
- plonk/examples/proof_of_exp.rs
- plonk/src/circuit/basic.rs
- plonk/src/circuit/customized/ecc/mod.rs
- plonk/src/circuit/customized/ultraplonk/plonk_verifier/gadgets.rs
- plonk/src/circuit/customized/ultraplonk/plonk_verifier/mod.rs
- plonk/src/errors.rs
- plonk/src/lib.rs
- plonk/src/par_utils.rs
- plonk/src/proof_system/batch_arg.rs
- plonk/src/proof_system/mod.rs
- plonk/src/proof_system/prover.rs
- plonk/src/proof_system/snark.rs
- plonk/src/proof_system/structs.rs
- plonk/src/testing_apis.rs
- primitives/Cargo.toml
- primitives/src/elgamal.rs
- primitives/src/merkle_tree.rs
- primitives/src/signatures/bls.rs
- primitives/src/signatures/schnorr.rs
- rescue/Cargo.toml
- rescue/src/lib.rs
- scripts/check_no_std.sh
- utilities/Cargo.toml
- utilities/src/serialize.rs
Syncing changes made in #80 and #85 to `main` branch
Closes: #84 
---
> no_std compliance and refactor SNARK trait

- CHANGELOG.md
- nix/nixpkgs.json
- nix/oxalica_rust_overlay.json
- plonk/src/circuit/basic.rs
- plonk/src/circuit/customized/ecc/glv.rs
- plonk/src/circuit/customized/ecc/mod.rs
- plonk/src/circuit/customized/ecc/msm.rs
- plonk/src/circuit/customized/mod.rs
- plonk/src/circuit/customized/ultraplonk/range.rs
- plonk/src/circuit/mod.rs
- primitives/src/circuit/merkle_tree.rs
- primitives/src/circuit/signature/schnorr.rs
- shell.nix
Introducing `struct BoolVar` whose creation automatically enforces a `bool_gate()`, distinguishing from normal `Variable` to avoid repeated checks and make API clearer.
closes: #91 
---
> Introduce BoolVar struct

- plonk/Cargo.toml
- plonk/examples/proof_of_exp.rs
- plonk/src/circuit/basic.rs
- plonk/src/circuit/customized/ecc/conversion.rs
- plonk/src/circuit/customized/ecc/glv.rs
- plonk/src/circuit/customized/ecc/mod.rs
- plonk/src/circuit/customized/ecc/msm.rs
- plonk/src/circuit/customized/gates.rs
- plonk/src/circuit/customized/transcript/mod.rs
- plonk/src/circuit/customized/ultraplonk/plonk_verifier/gadgets.rs
- plonk/src/circuit/customized/ultraplonk/plonk_verifier/mod.rs
- plonk/src/circuit/gates.rs
- plonk/src/proof_system/batch_arg.rs
- plonk/src/proof_system/snark.rs
- plonk/src/proof_system/structs.rs
- plonk/src/proof_system/verifier.rs
- plonk/src/testing_apis.rs
- plonk/src/transcript/mod.rs
- plonk/src/transcript/rescue.rs
- primitives/src/circuit/elgamal.rs
- primitives/src/circuit/merkle_tree.rs
- primitives/src/circuit/signature/schnorr.rs
- primitives/src/elgamal.rs
- primitives/src/signatures/schnorr.rs
- primitives/src/utils.rs
- utilities/src/conversion.rs
Major changes include:
- A missing modification for #87 in 6ee2ac08bdf910bf05bcd141a6e903b8b3e57131
- Remove unnecessary `Clone` on some trait bound: `P: Parameters + Clone` -> `P: Parameters`, whose source is our `trait Gate`, and trick I use is by relying on object-safe [`dyn_clone`](https://github.com/dtolnay/dyn-clone)
---
> Fixing some trait bound

- CHANGELOG.md
- utilities/src/serialize.rs
Previously, our `deserialize_canonical_bytes!()` macro only accept `MyStruct` and `MyStruct<'a>`, now we can accept arbitrary number of lifetime and generic parameter such as `MyStruct<'a, 'b, C: Config, R: Rng, ...>`
Blocking: https://github.com/EspressoSystems/cap/pull/64
---
> better deserialize_canonical_bytes macro

- plonk/src/circuit/plonk_verifier/gadgets.rs
- plonk/src/circuit/plonk_verifier/mod.rs
- plonk/src/circuit/plonk_verifier/poly.rs
- plonk/src/errors.rs
Gadgets under `plonk/circuit/plonk_verifier/*` should return `Result<_, CircuitError>` instead of `Result<_, PlonkError>`.
This is something we miss in #110.
---
> correct error type for PlonkVerifierGadget

- relation/src/gadgets/logic.rs
- relation/src/gates/logic.rs
> Bug fixed. `logic_or` should use `LogicOrValueGate`

- relation/src/gadgets/cmp.rs
closes: #104 
Some unfinished work for #96 and #81 
---
> Gadgets for comparing to constant

- CHANGELOG.md
- plonk/Cargo.toml
- plonk/src/circuit/plonk_verifier/gadgets.rs
- plonk/src/circuit/plonk_verifier/mod.rs
- plonk/src/circuit/transcript.rs
- plonk/src/errors.rs
- plonk/src/proof_system/batch_arg.rs
- plonk/src/proof_system/prover.rs
- plonk/src/proof_system/snark.rs
- plonk/src/proof_system/structs.rs
- plonk/src/proof_system/verifier.rs
- plonk/src/transcript/mod.rs
- plonk/src/transcript/rescue.rs
- primitives/Cargo.toml
- primitives/benches/pcs.rs
- primitives/src/lib.rs
- primitives/src/pcs/errors.rs
- primitives/src/pcs/mod.rs
- primitives/src/pcs/multilinear_kzg/batching.rs
- primitives/src/pcs/multilinear_kzg/mod.rs
- primitives/src/pcs/multilinear_kzg/srs.rs
- primitives/src/pcs/multilinear_kzg/util.rs
- primitives/src/pcs/prelude.rs
- primitives/src/pcs/structs.rs
- primitives/src/pcs/transcript.rs
- primitives/src/pcs/univariate_kzg/mod.rs
- primitives/src/pcs/univariate_kzg/srs.rs
closes: #62 
- Introduct new `PolynomialCommitmentScheme` trait and basic implementations
- Now `PlonkKzgSnark` use our own KZG10 implementation
---
> New PCS trait and implementation

- plonk/Cargo.toml
- primitives/Cargo.toml
- primitives/src/constants.rs
- primitives/src/signatures/bls.rs
- primitives/src/signatures/mod.rs
- primitives/src/signatures/schnorr.rs
- primitives/src/vrf/blsvrf.rs
- utilities/src/serialize.rs
Add trait bounds on `SignatureScheme` trait.
Bounds not yet added for `SigningKey`, pending discussion in [espresso-common](https://github.com/EspressoSystems/espresso-systems-common/issues/7).
closes: #145, #155
---
> `SignatureScheme` trait bounds

- CHANGELOG.md
- plonk/src/transcript/rescue.rs
- primitives/Cargo.toml
- primitives/src/circuit/commitment.rs
- primitives/src/circuit/rescue/native.rs
- primitives/src/circuit/rescue/non_native.rs
- primitives/src/commitment.rs
- primitives/src/merkle_tree/examples.rs
- primitives/src/merkle_tree/prelude.rs
- primitives/src/prf.rs
- primitives/src/rescue/mod.rs
- primitives/src/rescue/sponge.rs
- primitives/src/signatures/schnorr.rs
This is a WIP. 
The refactor defines new explicit types for CRHF and PRF which are sponges that internally use the Rescue `Permutation`, and as such is more aligned with the CAPE spec.
By following the sponge API we are able to re-use code shared between the above two functionalities.
It should then be then easier to make the circuits more generic by also defining and implementing a trait like [CryptographicSpongeVar](https://github.com/arkworks-rs/sponge/blob/master/src/constraints/mod.rs#L101), though we'd probably need to define our own due to a dependency on a R1CS `ConstraintSystem`.
closes: https://github.com/EspressoSystems/jellyfish/issues/15
---
checked off. If any of the checklist items are not …
> Sponge API refactor

- primitives/src/circuit/merkle_tree.rs
- primitives/src/circuit/merkle_tree/mod.rs
- primitives/src/circuit/merkle_tree/rescue_merkle_tree.rs
closes: #https://github.com/EspressoSystems/jellyfish/issues/88
as well as some indirect progress towards https://github.com/EspressoSystems/jellyfish/issues/142.
Note that non membership proofs are out of scope of this PR, but we can still close the referenced issue #88, if approved, since we already have a separate issue for non-membership proof constraints: https://github.com/EspressoSystems/jellyfish/issues/99.
Regarding the design, the initial refactor I had started doing was based on the API proposed by @alxiong in #88 - thanks a lot for this! You will see that it has changed in that methods don't accept native field elements/structs, but rather variables representing these items in the circuit. This was done for two reasons:
- There would otherwise be no way to (efficiently) …
> Ergonomic `MerkleTreeGadget`

- primitives/Cargo.toml
- primitives/src/merkle_tree/append_only.rs
- primitives/src/merkle_tree/internal.rs
- primitives/src/merkle_tree/macros.rs
- primitives/src/merkle_tree/mod.rs
- primitives/src/merkle_tree/prelude.rs
- primitives/src/merkle_tree/universal_merkle_tree.rs
- utilities/src/serialize.rs
Was playing around with Jellyfish for a hobby project and ran into a couple of ergonomics issues in the Merkle tree API.
commit 699dea9956ff2d872704e74eec3badf38db168f8
Author: Jeb Bearer <jeb@espressosys.com>
Date:   Wed Dec 14 11:43:07 2022 -0800
Make serde usable for MerkleTree types
The Merkle trees are ususally instantiated with cryptographic types,
e.g. field elements, which do not implement serde traits. This commit
changes the bound on the derived serde impls for Merkle tree types to
require ark_serialize impls on the element types and uses #[serde(with)]
to serialize these elements using ark_serialize.
We also add an instantiation of the Rescue hash scheme for field elements
as the _index_ type, since the BigUint instantiation just coverts to field
elements anyways, but BigUint …
> Merkle tree API improvements

- primitives/src/circuit/signature/schnorr.rs
fixes unnecessary cast.
This was not caught before since it's a new improvement in 1.66 clippy: https://github.com/rust-lang/rust-clippy/blob/master/CHANGELOG.md#rust-166
closes: #XXXX
---
> fix new clippy warnings

- primitives/src/merkle_tree/internal.rs
Just a minor code simplification. Notice that since `init` is immutable, it will always be set to `T::default()`. 
I would have expected clippy to pick it up, but maybe it's nested too deeply.
@mrain 
---
> Simplify `MerkleNode::Empty` match branch in `verify_non_membership_proof`

- CHANGELOG.md
- plonk/src/errors.rs
- plonk/src/transcript/mod.rs
- plonk/src/transcript/rescue.rs
- primitives/src/circuit/commitment.rs
- primitives/src/circuit/merkle_tree/mod.rs
- primitives/src/circuit/rescue/native.rs
- primitives/src/circuit/rescue/non_native.rs
- primitives/src/commitment.rs
- primitives/src/crhf.rs
- primitives/src/lib.rs
- primitives/src/rescue/mod.rs
- primitives/src/rescue/sponge.rs
- primitives/src/signatures/schnorr.rs
- relation/src/gadgets/ecc/mod.rs
Part of: #168 
Changes include:
- add `trait CRHF`
- Provide `struct FixedLengthRescueCRHF` and `struct VariableLengthRescueCRHF` conforming to the trait.
- add `trait CommitmentScheme`
- Provide `struct FixedLengthRescueCRHF`
NOTE:
to hack around some nightly-only feature on using const generic in an expression, we have a temporarily excessive generic parameter on `FixedLengthRescueCRHF<F, INPUT_LEN, INPUT_LEN_PLUS_ONE>` which will be fixed in the future.
---
> Created CRHF trait and conform RescueCRH impl

- primitives/src/circuit/prf.rs
- primitives/src/circuit/rescue/mod.rs
- primitives/src/circuit/rescue/native.rs
- primitives/src/circuit/rescue/non_native.rs
- primitives/src/prf.rs
- primitives/src/rescue/mod.rs
- primitives/src/rescue/sponge.rs
Major changes include:
- Introduced `trait PRF` 
- Conform existing impl in `prf.rs` to the new trait
- Add missing method rescue_full_state_keyed_sponge_with_padding on [RescueGadget](https://github.com/EspressoSystems/jellyfish/blob/9b7beb26360fb72eb80259330e37aa942e3bf854/primitives/src/circuit/rescue/native.rs#L188)
- Rename `PrfGadget` to `PRFGadget`
(the last two points or so are suggested by @tessico in #160)
Closes: #168, #160 
---
> Stablize PRF API

- primitives/src/merkle_tree/internal.rs
- primitives/src/merkle_tree/universal_merkle_tree.rs
* MerkleProof::elem() was looking at the last node in the proof; it should look at the first, since the proof goes from the leaf to the root.
* update_internal was not updating the value of parent nodes when one of their children was changed due to an update. This caused the tree invariants to be violated after an update, and proof verification to fail.
closes: #XXXX
---
> Bug fixes for universal Merkle tree

- primitives/src/vrf/mod.rs
closes: https://github.com/EspressoSystems/jellyfish/issues/166
---
> Add trait bounds to VRF's associated types

- primitives/src/merkle_tree/internal.rs
- primitives/src/merkle_tree/mod.rs
- primitives/src/merkle_tree/prelude.rs
- primitives/src/merkle_tree/universal_merkle_tree.rs
_Needed this for a personal project, not work-related. Review at your leisure. I believe it does fix a bug, though._
This trait extends the existing `UniversalMerkleTreeScheme` with two new functions:
* `universal_forget` is like `forget` from `ForgetableMerkleTreeScheme`, but returns a non-membership proof if the result is `NotFound`
* `non_membership_remember` re-inserts an empty sub-tree given a non-membership proof
Also fixes a bug in `forget_internal` where `height` was not decremented in recursive calls.
> Add ForgetableUniversalMerkleTreeScheme

- CHANGELOG.md
- primitives/src/pcs/multilinear_kzg/batching.rs
- primitives/src/pcs/multilinear_kzg/mod.rs
- primitives/src/pcs/multilinear_kzg/srs.rs
- primitives/src/pcs/multilinear_kzg/util.rs
> Refactor multilinear PCS opening

- primitives/src/circuit/merkle_tree/mod.rs
- primitives/src/circuit/merkle_tree/rescue_merkle_tree.rs
- primitives/src/circuit/merkle_tree/sparse_merkle_tree.rs
Making the circuit equivalent of MerkleTree generic over a digest algorithm is more tricky, because both the `MerkleTreeGadget` and `DigestAlgorithmGadget` need to be implemented for `PlonkCircuit`.
I'm proposing two designs here. One is to add it as a generic parameter to `MerkleTreeGadget`, see [the last commit](https://github.com/EspressoSystems/jellyfish/pull/167/commits/4e3a09c80fac905b26f2632f1d4e33ece9bd3398). The other option is to add `DigestAlgorithmGadget` as an associated type on the `MerkleTreeGadget` trait, see [here](https://github.com/EspressoSystems/jellyfish/pull/167/commits/371e87470b2261ee1ea459d9f7e87a5d634d0397). Both options work, it's just a matter of convenience and ergonomics. Please let me know your opinions.
(Note that initially I thought that the associated …
> Digest-generic MerkleTreeGadget

- CHANGELOG.md
- relation/src/errors.rs
- relation/src/gadgets/arithmetic.rs
- relation/src/gadgets/ecc/mod.rs
- relation/src/gadgets/logic.rs
- relation/src/gadgets/mod.rs
- relation/src/gadgets/range.rs
- relation/src/gadgets/utils.rs
- relation/src/lib.rs
> Add `no_std` attribute to `jf-relation`

- plonk/Cargo.toml
- plonk/src/errors.rs
- plonk/src/proof_system/verifier.rs
- primitives/Cargo.toml
- primitives/src/aead.rs
- primitives/src/errors.rs
- primitives/src/pcs/multilinear_kzg/srs.rs
- primitives/src/pcs/univariate_kzg/mod.rs
- primitives/src/signatures/bls.rs
- relation/Cargo.toml
- relation/src/constraint_system.rs
- relation/src/gadgets/ultraplonk/mod_arith.rs
- utilities/Cargo.toml
- utilities/src/serialize.rs
Quick fix CI error [here](https://github.com/EspressoSystems/jellyfish/runs/11123870191).
Changes include:
- Inlined all format args, see clippy [hints here](https://rust-lang.github.io/rust-clippy/master/index.html#uninlined_format_args): e.g. `format!("{:?}, error")` -> `format!("{error:?}")` for better readability
- reason why we didn't catch previously in CI or locally is because our CI is not running inside nix-shell, thus two CI runs might end up using different clippy and rust (based on upstream release), and there has been a new release `1.67.0` which add this clippy rule. No big deal.
- temporarily use `version = {workspace = true}` instead of `version.workspace = true` syntax, due to https://github.com/DevinR528/cargo-sort/issues/47 (so that our precommit hook won't fail)
> Fix clippy error in CI

- CHANGELOG.md
- plonk/src/transcript/rescue.rs
- utilities/Cargo.toml
- utilities/src/conversion.rs
closes: #227 
- add `bytes_from_field_elements()` to invert `bytes_to_field_elements()`
- modify `bytes_to_field_elements()` to encode bytes length in the first field element for use in inversion
- remove unneeded bytes copy in `bytes_to_field_elements` and other tidying
- generalize both functions from `PrimeField` to `Field`
- TODO: used `String` as error type for `bytes_from_field_elements`---should we do something else instead?
- minimal tests only
---
> New `bytes_from_field_elements` util

- utilities/src/conversion.rs
Currently `bytes_from_field_elements` enforces that the result length be within the final field element.
However, some use cases (such as polynomial interpolation) might pad the list of field elements with extra zeros. In this case result length will be below the final field element, so `bytes_from_field_elements` will throw an error.
We could rely on the caller to remember how many field elements it started with and trim appropriately, but that cuts against the purpose of encoding the result length in the field elements. It makes more sense to simply allow the user to pad with extra zeros and then truncate down to the encoded result length at the end.
---
checked off. If any of the checklist items are …
> fix: bytes_from_field_elements remove lower bound check on result_len

- primitives/src/signatures/bls_over_bn254.rs
This PR is related to https://github.com/EspressoSystems/espresso-sequencer/pull/292. The changes are:
* Add a public function to have access to the attribute of the `Signature` struct.
* Change the logic of hash_to_curve  about computing the square root of a field element so that it is consistent with https://github.com/EspressoSystems/cape/blob/77f343849db3d9e721c6e3d0f7108155c178dbee/contracts/contracts/libraries/BN254.sol#L338
> Minor changes to support BLS signature verification inside a smart contract

- primitives/src/signatures/bls_over_bn254.rs
As discussed in https://github.com/EspressoSystems/jellyfish/pull/242#pullrequestreview-1393076760.
> Remove function `Signature.get_sig_value()` and make `Signature.sigma` public instead.

- primitives/src/pcs/errors.rs
- relation/src/gadgets/ecc/glv.rs
- utilities/Cargo.toml
- utilities/src/conversion.rs
- `bytes_from_field_elements` error type is `String`, which does not implement the `Error` trait. Instead, make it infallible. Because it's infallible we need paranoid checks for overflow.
- Improve tests for `bytes_[to|from]_field_elements`.
- Minor quality-of-life improvement for downstream error handling: `PCSError` does not implement the `Error` trait -> implement it
- Appease clippy way over in `glv.rs`.
---
> make `bytes_from_field_elements` infallible with paranoid checks for overflow

- .github/workflows/build.yml
- .gitignore
- CHANGELOG.md
- plonk/Cargo.toml
- plonk/examples/proof_of_exp.rs
- plonk/src/circuit/plonk_verifier/gadgets.rs
- plonk/src/circuit/plonk_verifier/mod.rs
- plonk/src/proof_system/batch_arg.rs
- plonk/src/proof_system/mod.rs
- plonk/src/proof_system/snark.rs
- plonk/src/proof_system/structs.rs
- primitives/Cargo.toml
- primitives/benches/pcs.rs
- primitives/src/lib.rs
- primitives/src/pcs/errors.rs
- primitives/src/pcs/mod.rs
- primitives/src/pcs/multilinear_kzg/batching.rs
- primitives/src/pcs/multilinear_kzg/mod.rs
- primitives/src/pcs/multilinear_kzg/srs.rs
- primitives/src/pcs/multilinear_kzg/util.rs
- primitives/src/pcs/poly.rs
- primitives/src/pcs/prelude.rs
- primitives/src/pcs/univariate_kzg/mod.rs
- primitives/src/pcs/univariate_kzg/srs.rs
- primitives/src/signatures/bls_over_bn254.rs
- primitives/src/toeplitz.rs
- scripts/run_tests.sh
- utilities/src/lib.rs
Partially completes: #118 
Major changes include:
- add trait bound to associated type of the PCS trait: `PolynomialCommitmentScheme::SRS: StructuredReferenceString`.
- define Toeplitz and Circulant matrix, impl conversion between them. 
- Implement fast mul with a vector for circulant matrix
- implement fast mul with a vector for toeplitz by expanding into a 2N circulant matrix and use above subroutine
- add correctness test for matrix multiplications.
- Define a `GeneralDensePolynomial` that allows its coeffs to be either field or group, and implement `batch_evaluate`
- FK23 methods using all above, with unit tests.
More important changes when addressing comments:
- hide `gen_srs_for_testing` under `test-srs` feature flag (and also available for test) so that downstream and bench code …
> Add FK23 batch opening of univariate polynomials 

- CHANGELOG.md
- primitives/src/signatures/bls_over_bn254.rs
Needs the API for implement quorum certificate.
---
> add sign_key_ref api for BLSKeyPair

- .github/workflows/build.yml
- .gitignore
- CHANGELOG.md
- README.md
- flake.lock
- flake.nix
- plonk/Cargo.toml
- primitives/Cargo.toml
- primitives/benches/pcs.rs
- primitives/src/lib.rs
- primitives/src/pcs/mod.rs
- primitives/src/pcs/multilinear_kzg/batching.rs
- primitives/src/pcs/multilinear_kzg/mod.rs
- primitives/src/pcs/multilinear_kzg/util.rs
- primitives/src/pcs/prelude.rs
- primitives/src/signatures/bls_over_bls12381.rs
- relation/Cargo.toml
- scripts/build_wasm.sh
- utilities/Cargo.toml
Closes: #252 
Partially address: #248
---
> Initial WASM Support

- flake.nix
- Remove overlay, it seems it's not required with the current configuration.
- Set env vars from nix variables, this should be a bit more robust.
- Use `libclang.version` in include path.
closes: #XXXX
---
> Nix fixups

- .github/workflows/build.yml
- .gitignore
- plonk/src/testing_apis.rs
- primitives/src/lib.rs
- primitives/src/pcs/mod.rs
- primitives/src/pcs/multilinear_kzg/srs.rs
- primitives/src/pcs/poly.rs
- primitives/src/pcs/univariate_kzg/mod.rs
- primitives/src/pcs/univariate_kzg/srs.rs
closes: #260 
Each commit and commit message should be informative enough, and best reviewed per commit.
Extra note: https://github.com/EspressoSystems/jellyfish/issues/260#issuecomment-1557541691
---
> Refactor multi_open APIs

- CHANGELOG.md
- primitives/src/signatures/bls_over_bn254.rs
- primitives/src/signatures/mod.rs
Serde support for Aggregateable signatures. Needed for task https://github.com/EspressoSystems/hotshot-primitives/issues/31.
> Serde support for Aggregateable signatures

- primitives/benches/merkle_path.rs
- primitives/src/errors.rs
- primitives/src/merkle_tree/append_only.rs
- primitives/src/merkle_tree/internal.rs
- primitives/src/merkle_tree/light_weight.rs
- primitives/src/merkle_tree/macros.rs
- primitives/src/merkle_tree/mod.rs
- primitives/src/merkle_tree/universal_merkle_tree.rs
closes: #272 
API change:
- Convert `MerkleTreeScheme::verify` from method to associated function. (ie. do not take `self`.)
- `MerkleTreeScheme::verify` do not take `pos`. Why? This argument is redundant. Currently, the only use of `pos` is to compare it against `proof.pos` and throw an error if they don't match. By removing `pos` we do not force the user to know anything about `pos` in order to verify a proof.
- **[EDIT]** `MerkleTreeScheme::verify` take `root` arg as per https://github.com/EspressoSystems/jellyfish/pull/274#discussion_r1206884154
- **[EDIT]** New `VerificationResult` return type, used in `MerkleTreeScheme::verify` as per https://github.com/EspressoSystems/jellyfish/pull/274#discussion_r1206866522
- Core API changes in `mod.rs`, `macros.rs`, `internal.rs`. All other …
> feat(api)!: MerkleTreeScheme::verify do not take self, pos

- .github/workflows/build.yml
- CHANGELOG.md
- README.md
- flake.nix
- primitives/Cargo.toml
- primitives/src/aead.rs
- scripts/build_wasm.sh
closes: #258
(see more discussion in https://github.com/RustCrypto/nacl-compat/issues/124)
Changes include:
- switch the underlying AEAD from `crypto_box` to `crypto_kx` + `chacha20poly1305` without changing Jellyfish's own API
- the latest `crypto_box` no longer supports associated data since it strive to restore compatibility with libsodium
- we want the latest `crypto_box` because we want to use `--cfg curve25519_dalek_backend="u32_backend"` to select backend instead of feature flag which is additive, (see the linked issue for details)
- therefore, I decide to move away from it, and just use `crypto_kx` to establish shared secret, and use symmetric AEAD like `xchacha20poly1305` (with extended nonce), see the RustCrypto issue linked above for more details
- Removed `CanonicalSerde` and …
> remove crypto_box and support choosing curve25519 backend using rustflags

- primitives/src/merkle_tree/macros.rs
one-line addendum to #286 
`MerkleTreeScheme::verify` should not return `Err(_)` if the `pos` arg is inconsistent with the `proof`. It just means that `proof` is invalid for this `pos`, so verification fails. This matters for downstream users who use `?` to return early from a real internal error before checking whether verification fails.
---
> fix: invalid pos is not en error, so return Ok(_) instead of Err(_)

- primitives/src/reed_solomon_code/mod.rs
> fix: Reed-Solomon panic on duplicate input points

- primitives/src/pcs/mod.rs
My life as a downstream user of jellyfish would be so much easier if `checked_fft_size` were public. I use it only in tests, so if you really don't want it public then perhaps we could feature-gate it or something.
---
> chore: make checked_fft_size public

- primitives/src/merkle_tree/namespaced_merkle_tree.rs
Constructs an absence proof when the target namespace falls within the tree range by providing two adjacent leaves that bound the target namespace. 
---
- [ x] Targeted PR against correct branch (main)
- [x ] Linked to GitHub issue with discussion and accepted design OR have an explanation in the PR that describes this work.
- [x ] Wrote unit tests
- [x ] Updated relevant documentation in the code
> feat: Finish NMT Absence proofs

- CHANGELOG.md
- relation/src/gadgets/emulated.rs
- relation/src/gadgets/range.rs
- relation/src/gadgets/ultraplonk/range.rs
> perf: improve range gate implementation

- primitives/src/merkle_tree/namespaced_merkle_tree/mod.rs
…ng namespace data
Refactor logic that handles namespace metadata into a helper function that can be used for `from_elems`, `push`, and `extend`. 
closes: #314 
---
- [ x] Targeted PR against correct branch (main)
- [ x] Linked to GitHub issue with discussion and accepted design OR have an explanation in the PR that describes this work.
- [ x] Wrote unit tests
- [ x] Updated relevant documentation in the code
> feat: Implement `extend` + `push` for NMT

- CHANGELOG.md
- plonk/src/circuit/plonk_verifier/gadgets.rs
- plonk/src/circuit/transcript.rs
- primitives/Cargo.toml
- primitives/benches/advz.rs
- primitives/src/lib.rs
- primitives/src/vid/advz.rs
- primitives/src/vid/mod.rs
- primitives/tests/advz.rs
- primitives/tests/vid/mod.rs
- scripts/run_tests.sh
closes: #336 
A direct port of `vid` from hotshot-primitives repo. Nontrivial changes:
- Feature-gate tests with `test-srs` feature. (This was much easier from another repo because `test-srs` could be specified in a dev-dependency in `Cargo.toml`, but there seems to be no idiomatic way to enable a feature of the present crate only for test/bench code 😢 .)
- Support `no_std`. Remove use of `thiserror` crate, which is not `no_std` compatible, and tweak associated error-handling code.
---
> feat(vid): port VID from another repo

- primitives/src/pcs/mod.rs
- primitives/src/pcs/transcript.rs
The jellyfish `IOPTranscript` has very ergonomic wrappers around merlin, why not expose it publicly.
Also I added an extra convenience method for getting challenge bytes instead of field elements.
Not sure whether this is a good approach - instead one could make the `transcript` field of the struct public and allow users to call more methods directly from merlin.
---
> feat: Make `IOPTranscript` publicly accessible

- CHANGELOG.md
- plonk/src/proof_system/verifier.rs
- primitives/src/merkle_tree/examples.rs
- primitives/src/merkle_tree/internal.rs
- primitives/src/merkle_tree/mod.rs
- primitives/src/merkle_tree/universal_merkle_tree.rs
- primitives/src/pcs/mod.rs
- primitives/src/pcs/multilinear_kzg/mod.rs
- primitives/src/pcs/poly.rs
- primitives/src/pcs/structs.rs
- primitives/src/pcs/univariate_kzg/mod.rs
- primitives/src/pcs/univariate_kzg/srs.rs
- primitives/src/vid/advz.rs
- primitives/src/vid/mod.rs
A bunch of structs need `Eq` and `Hash` to enable integration of VID into hotshot. This PR does that. It's not pretty but it gets the job done.
This PR is a good opportunity to remind the reader that we should do a proper clean-up of trait bounds #253 to eliminate the need for PRs such as this.
---
> chore: Derive Eq, Hash at a bunch of places

- CHANGELOG.md
- primitives/benches/advz.rs
- primitives/src/vid/advz.rs
- primitives/src/vid/mod.rs
- primitives/tests/vid/mod.rs
closes: #369 
- With this addition of the payload commitment to the return value of `disperse`, the return type would become a 3-tuple. This is unruly and clippy complained about type complexity when I tried it. (See fc4548ca1d0799df5179ee0668d26f0f4d178191.) So instead I created a new struct `VidDisperse` to aggregate these values in a more legibile return type and give them names.
- I took this opportunity to shorten/clarify some names.
- Bizarre behaviour from the compiler forced me to add an unnecessary `as` cast: https://github.com/EspressoSystems/jellyfish/blob/ddea9733fc3739efc99d10c00cb5d25d917edc0a/primitives/src/vid/advz.rs#L341-L346
---
checked off. If any of the checklist items are not …
> chore: VID disperse also return payload commitment

- primitives/src/signatures/bls_over_bls12381.rs
- primitives/src/signatures/bls_over_bn254.rs
- primitives/src/signatures/mod.rs
- primitives/src/signatures/schnorr.rs
These trait bounds are needed in some downstream libraries [here](https://github.com/EspressoSystems/hotshot-qc-prover/blob/main/src/circuit/vars.rs#L16-L27). 
Even though the downstream usage might be changed later, I don't find it unreasonable to add these trait bounds anyway.
> refactor: add some trait bounds to SignatureSchemes traits

- CHANGELOG.md
- primitives/src/pcs/univariate_kzg/mod.rs
- primitives/src/vid/advz.rs
- primitives/tests/advz.rs
> fix: VID ADVZ allow zero-length payload

- .envrc
- .gitignore
- flake.nix
- primitives/benches/advz.rs
VID benchmark code has not been used in a while. This PR cleans up the bit rot. 
---
> test: update VID bench code

- Cargo.toml
- plonk/Cargo.toml
- plonk/src/lib.rs
- plonk/src/proof_system/structs.rs
- plonk/src/proof_system/verifier.rs
- plonk/src/testing_apis.rs
- plonk/src/transcript/solidity.rs
These are the changes I made during writing tests for https://github.com/EspressoSystems/espresso-sequencer/pull/722, Most changes are under `test-api`, so should be safe
> test: Expose more internal functions for test

- flake.nix
This might be more convenient than having a separate devShell for
nightly tasks (which still wouldn't support the `+nightly` argument).
It works for me to run `cargo test` and `scripts/run_tests.sh`.
Not familiar with the repo so don't know if other workflows might break.
> chore: Cargo shell script to support +nightly

- Cargo.toml
- plonk/Cargo.toml
- primitives/Cargo.toml
- utilities/Cargo.toml
Update tagged base 64, fixing `serde_json::from_value` bug
---
> chore: update tagged base64

- primitives/Cargo.toml
- primitives/src/pcs/univariate_kzg/mod.rs
- primitives/src/pcs/univariate_kzg/srs.rs
closes: #427 
- New build feature `no-fk23` to enable a naive parallel implementation of `UnivariateKzgPCS::multi_open_rou_proofs()`.
- Tidy: comment link to issues, timer logs, fix build breaks for various feature combos.
1. Uncomment the `#[test]` attribute for the `disperse_timer` test in `vid/advz.rs`. (This test is commented out so as to save CI.) https://github.com/EspressoSystems/jellyfish/blob/2f004e2abe566f8cfaaca5b25c66fbfe6920db1e/primitives/src/vid/advz.rs#L642-L644
2. Run test in release mode with (and without) `no-fk23` feature:
```bash
cargo test --release --package jf-primitives --lib --features test-srs,print-trace,no-fk23 -- vid::advz::tests::disperse_timer --exact --nocapture
cargo test --release --package jf-primitives --lib --features test-srs,print-trace -- …
```
> perf: naive parallel implementation for `multi_open_rou_proofs`

- CHANGELOG.md
- plonk/src/circuit/transcript.rs
- plonk/src/proof_system/snark.rs
- plonk/src/proof_system/structs.rs
- primitives/src/pcs/mod.rs
- primitives/src/pcs/multilinear_kzg/srs.rs
- primitives/src/pcs/univariate_kzg/mod.rs
- primitives/src/pcs/univariate_kzg/srs.rs
closes: #387 
Implement the KZG multiproof algorithm described in https://dankradfeist.de/ethereum/2020/06/16/kate-polynomial-commitments.html.
Since we assume that the number of opening points is small, we do not implement the fancy algorithm described in #387 
---
> feat: Implement KZG multiproof

- CHANGELOG.md
- primitives/src/vid/advz/payload_prover.rs
closes: #424 
Naive implementation:
- `SmallRangeProof`: concatenate individual KZG proofs from multiple polynomials, do not aggregate
- `LargeRangeProof`: rebuild and verify multiple KZG commitments. There's not much more we could do to improve here. But verification inside a smart contract is now more complex because it might need to compute multiple KZG commitments instead of one.
---
> feat: ADVZ PayloadProver support requests that span multiple polynomial

- primitives/Cargo.toml
- primitives/src/vid.rs
- primitives/src/vid/advz.rs
- primitives/src/vid/advz/payload_prover.rs
closes: #446 
- New trait `LengthGetter` for #446 
- New trait `CommitChecker` for (unposted issue): we need a way for downstream users to check consistency of a `VidScheme::Common` with its corresponding `VidScheme::Commit`. Previously this functionality was not exposed downstream.
- I snuck in more optimisation in `Advz::disperse`: this PR uses `batch_commit` to compute KZG commitments in parallel inside `disperse`, just like what was done in #448 for `Advz::commit_only`. 20% improvement. See below for benches.
This PR adds 2 traits `LengthGetter`, `CommitChecker` intended for optional impl for `VidScheme::Common` assoc type. Is there a cleaner way to achieve this API without forcing all `VidScheme` impls to provide this functionality?
1.135s improve to 933.702ms, ~20% improvement.
``` …
```
> feat: VID API tweaks, plus optimization for ADVZ disperse

- primitives/src/merkle_tree/hasher.rs
- primitives/src/vid.rs
- primitives/src/vid/advz.rs
closes: #455 
- `Advz` implementation of `VidScheme` change `Commit` assoc type from `Output<H>` to `HasherNode<H>`. `HasherNode` was originally intended for use in jellyfish's merkle tree implementation. But it also conveniently doubles as a friendly wrapper for the upstream `Output<H>` that provides many more trait impls.
- `#[tagged]` is magic 😮 
---
> chore: VidScheme::Commit assoc type support TaggedBase64 conversion

- primitives/src/merkle_tree/internal.rs
- primitives/src/merkle_tree/light_weight.rs
closes: #XXXX
Now the light weight merkle tree correctly forget the previously inserted elements, and we have a test for that.
Thanks for @Ayiga who spotted it.
---
> fix: light weight merkle tree didn't forget previously inserted elements

- flake.lock
- primitives/src/vid.rs
- primitives/src/vid/advz.rs
- primitives/src/vid/advz/payload_prover.rs
- primitives/tests/vid/mod.rs
closes: #460 
Does what it says on the tin.
Currently data such as [payload byte length], [number of storage nodes] is stored in `Common` as `usize`. But `Common` is a serializable struct. I'm uneasy about putting `usize` in such a struct because the guarantees you get are less clear and it could waste space. This struct will be sent over the wire and every byte counts. Shall we pick a fixed word size here like `u16`, `u32`? (We could even use 3 bytes.)
---
> feat: new trait method VidScheme::get_num_storage_nodes

- CHANGELOG.md
- plonk/src/proof_system/snark.rs
- primitives/benches/bls_signature.rs
- primitives/benches/merkle_path.rs
- primitives/src/circuit/merkle_tree/mod.rs
- primitives/src/circuit/rescue/native.rs
- primitives/src/merkle_tree/append_only.rs
- primitives/src/merkle_tree/hasher.rs
- primitives/src/merkle_tree/internal.rs
- primitives/src/merkle_tree/light_weight.rs
- primitives/src/merkle_tree/macros.rs
- primitives/src/merkle_tree/mod.rs
- primitives/src/merkle_tree/namespaced_merkle_tree/mod.rs
- primitives/src/merkle_tree/universal_merkle_tree.rs
- primitives/src/pcs/multilinear_kzg/batching.rs
- primitives/src/pcs/multilinear_kzg/srs.rs
- primitives/src/signatures/bls_over_bn254.rs
- primitives/src/toeplitz.rs
- primitives/src/vid/advz.rs
- primitives/src/vid/advz/bytes_to_field.rs
- primitives/tests/merkle_tree_hasher.rs
closes: #465 
- Remove the unnecessary trait bound `From<u64>` to the merkle tree index
- A new `update_with` interface for the universal merkle tree as requested here
- https://github.com/EspressoSystems/espresso-sequencer/pull/989#discussion_r1453715569
- A new `iter()` interface for Merkle tree scheme, allows user to iterate through all elements that's in memory.
---
> feat: ergonomics changes for merkle tree

- primitives/benches/advz.rs
- primitives/src/vid.rs
- primitives/src/vid/advz.rs
- primitives/src/vid/advz/payload_prover.rs
- primitives/tests/advz.rs
- primitives/tests/vid/mod.rs
This PR introduces the concept of multiplicity of the degree for polynomials encoding the payload.
Support for large degree polynomials is done by extending message/codeword length by a factor $\alpha$ while maintaining the same rate $r=\frac{\alpha\cdot m}{\alpha\cdot n}$. Each node in the system will receive $\alpha$ evaluation points (multi-shares) for each polynomial $f_i$  $\forall i\in \{1,\ldots,k\}$.
closes: #393
> feat: Enable support for large polynomials in VID

- primitives/src/vid/advz.rs
- primitives/tests/advz.rs
- primitives/tests/vid/mod.rs
#480 introduced a new feature that allows for building polynomials of larger degree when encoding the VID payload by choosing a multiplicity parameter but no tests were submitted with the new features.
This PR fixes issues in the VID verification and payload recovery when `multiplicity > 1` and **creates a test** to exercise the new part of the code.
closes: #483
> fix: incorrect VID verification/recovery (multiplicity > 1)

- primitives/src/vid.rs
- primitives/src/vid/advz.rs
- primitives/src/vid/advz/precomputable.rs
- primitives/src/vid/precomputable.rs
Follows the approach described here: #479.
Introducing the subtrait `Precomputable` to a VID scheme.
This allows for re-using the polynomial commitments (from `commit_only_precompute`) when calling `disperse_precompute`.
Lots of code-duplication but was a bit reluctant to refactor and make pre-mature code optimizations since we might have more data that can potentially be pre-computed and keeping the disperse code as is (in one function) makes it easy to map tracing output to code (readability of benchmarks).
---
Preliminary testing for pre-computation approach:
`payload_size = 33MB, num_storage_nodes = 128, multiplicity = 8`
We get running times:
commit_only_precompute: 2.768s
**disperse_precompute: 2.580s**
(see test run below)
```
Espressos-MBP:jellyfish espressosystems$ cargo test …
```
> feat: Enable precomputation of VID dispersal data

- primitives/src/merkle_tree/append_only.rs
- primitives/src/merkle_tree/internal.rs
- primitives/src/merkle_tree/light_weight.rs
- scripts/run_tests.sh
> fix: Merkle tree bug fix

- primitives/src/merkle_tree/internal.rs
- primitives/src/merkle_tree/prelude.rs
Requested by sequencer team.
You could access them through `jf_primitives::merkle_tree::prelude::{MerkleNode, MerklePath, MerkleProof}`.
And we already have `MerkleProof::new(index, path)`.
---
> chore: expose `MerkleNode`, `MerklePath`, and `MerkleProof`

- .github/workflows/build.yml
- CHANGELOG.md
- flake.nix
- primitives/Cargo.toml
- primitives/benches/kzg_gpu.rs
- primitives/benches/msm.rs
- primitives/src/lib.rs
- primitives/src/pcs/errors.rs
- primitives/src/pcs/mod.rs
- primitives/src/pcs/univariate_kzg/mod.rs
closes: #490 
Unit tests already test the correctness of the MSM results.
Benchmark can be run via `cargo bench --bench msm --features "test-srs icicle"`
**TL;DR: it's about 50x speedup compared to arkworks!** 🎉
Current `criterion` benchmark:
```
MSM with arkworks/19    time:   [1.5497 s 1.5526 s 1.5554 s]
MSM with arkworks/20    time:   [2.8726 s 2.8801 s 2.8848 s]
MSM with arkworks/21    time:   [5.8268 s 5.8572 s 5.8847 s]
MSM with arkworks/22    time:   [11.618 s 11.641 s 11.665 s]
MSM with ICICLE/19      time:   [26.753 ms 26.841 ms 27.018 ms]
Found 1 outliers among 10 measurements (10.00%)
1 (10.00%) high severe
MSM with ICICLE/20      time:   [48.716 ms 48.728 ms 48.737 ms]
Found 1 outliers among 10 measurements (10.00%)
1 (10.00%) low mild
MSM with ICICLE/21      time:   [87.649 …
```
> feat: ICICLE msm integration

- primitives/benches/kzg_gpu.rs
- primitives/src/lib.rs
- primitives/src/pcs/univariate_kzg/mod.rs
closes: #490 (particularly addressing the https://github.com/EspressoSystems/jellyfish/issues/490#issuecomment-1986098853)
@mrain you had such a good suggestion. 👍 
the key of breaking from the evil compiler deep-hole is just "completely disassociated `E` and  `C`", and remove generic implementation, let specialized implementor to fill in `xx_to_ark/icicle()` function, so we can just throw away all those `ArkEquivalent` bound and `CurveConfig` bound. 
just a comparison,
```rust
// Previous: 
pub fn kzg_icicle<E, C>(c: &mut Criterion)
where
C: IcicleCurve + MSM<C>,
C::ScalarField: ArkConvertible<ArkEquivalent = E::ScalarField>,
C::BaseField: ArkConvertible<ArkEquivalent = <C::ArkSWConfig as CurveConfig>::BaseField>,
<C::ArkSWConfig as CurveConfig>::BaseField: PrimeField,
E: …
```
> refactor: hide IcicleCurve as associated type, much cleaner trait bound

- primitives/Cargo.toml
- primitives/benches/advz.rs
- primitives/src/lib.rs
- primitives/src/pcs/univariate_kzg/mod.rs
- primitives/src/vid.rs
- primitives/src/vid/advz.rs
- primitives/src/vid/advz/payload_prover.rs
- primitives/src/vid/advz/precomputable.rs
- primitives/tests/vid/mod.rs
closes: #521 
Major changes include:
- Rename original `struct Advz` to `struct AdvzInternal`, including all of its implementations
- Introduce two type alias `type Advz` (which is a direct replacement of the original struct with the same interface and generic param) and `type AdvzGPU` which contains more icicle-related type declaration
- Introduce `trait MaybeGPU` to allow specialized trait bounds on `kzg_batch_commit()` 
- GPU version is enabled by feature flag `gpu-vid`
- ⚠️ unfortunately, due to suboptimal API design of ICICLE's `struct HostOrSlice` which affects how we write `GPUCommit::commit_on_gpu`, we changed the API of `VidScheme::commit_only/disperse(&mut self)` to accept `&mut self` instead of the `&self`. Note that for the CPU version, even though we pass in a mutable …
> feat!: GPU accelerated VID disperse

- primitives/src/pcs/univariate_kzg/mod.rs
Originally, you'll panic if you feed the empty poly list to `gpu_batch_commit()`.
This PR adds a shortcut to prevent it.
---
> fix: `gpu_batch_commit` with empty polys

- primitives/benches/advz.rs
- primitives/src/vid.rs
- primitives/src/vid/advz.rs
- primitives/src/vid/advz/payload_prover.rs
- primitives/src/vid/advz/precomputable.rs
- primitives/tests/advz.rs
- primitives/tests/vid/mod.rs
closes: #463 
---
- BREAKING API CHANGE: `Advz::new` no longer take `multiplicity` arg. Instead we choose `multiplicity` for the caller. (Currently we set `mulitiplicity` to 1, issue #534 .) Also, reorder the arg list.
- new constructor `Advz::with_multiplicity` does what `Advz::new` used to do.
- remove limit on `multiplicity` as requested by @mrain 
- rename `payload_chunk_size` -> `recovery_threshold`. Much clearer IMO.
- As discussed, convert everything that will be serialized in VID from `usize` to `u32`. Lots of ugly `as usize` everywhere, but at least these conversions are safe. Dammit, Rust.
- I'm unable to build locally with `gpu-vid` feature. @mrain we might need you to check the build with `gpu-vid`.
Before we can merge this PR, please make sure that all the following items …
> chore!: new Advz constructor, Advz use u32 instead of usize

- Cargo.toml
- primitives/src/pcs/univariate_kzg/mod.rs
- primitives/src/vid/advz.rs
_Update: this also fixes the API changes when `gpu_vid` is enabled._
This PR avoids a memory copy in `load_poly_to_gpu`. However it contains unsafe rust code.
Before:
```
Start:   KZG10::Setup with prover degree 4194304 and verifier degree 1
...
Start:   Type Conversion: ark->ICICLE: Scalar
End:     Type Conversion: ark->ICICLE: Scalar ......................................17.305ms
...
```
After:
```
Start:   KZG10::Setup with prover degree 4194304 and verifier degree 1
...
Start:   Type Conversion: ark->ICICLE: Scalar
End:     Type Conversion: ark->ICICLE: Scalar ......................................160ns
...
```
It doesn't apply to affine point conversion because of two different underlying struct reprs.
---
Before we can merge this PR, please make sure that all the following items …
> chore: overhead free type conversion for `load_poly_to_gpu`

- .github/workflows/periodic_checks.yml
Fix CI failure for periodic check: https://github.com/EspressoSystems/jellyfish/actions/runs/8863541950/job/24337714873 
(which always notify me on weekend 😢 )
since we didn't install [`cargo-udeps` ](https://github.com/est31/cargo-udeps)in nix shell, I was using my local exec, and I got:
```
└─○ cargo-udeps udeps --workspace --all-targets --features 'test-srs test-apis bls schnorr gadgets'                      
All deps seem to have been used.
``` 
---
> ci: update ci for unused dep

- plonk/src/lagrange.rs
- plonk/src/lib.rs
- plonk/src/proof_system/prover.rs
- plonk/src/proof_system/verifier.rs
- plonk/src/testing_apis.rs
closes: #605 
Executed this plan: https://github.com/EspressoSystems/jellyfish/issues/605#issuecomment-2180773751
and updated all previously lagrange coeffs computation
Update anything about recursive circuit, since the occurrence of the challenge `zeta` being one of the domain elements is negligibly small, not sure if we want to burden our recursion circuit to include the extra branch condition.  
---
> fix: correct lagrange coefficient computation

- scripts/run_tests.sh
- scripts/test_coverage.sh
closes: #614
- Fix the test code coverage script.
- Add the unstable option back for run_test.sh . Now it also report the test running time.
---
> fix: scripts maintenance

- flake.nix
Part of #614 
On my machine grcov is not installed. By updating flake.nix the test coverage script works.
This PR does not solve #614 entirely, only a part.
`flake.nix` file.
> feat: Add grcov to flake.nix

- plonk/CHANGELOG.md
- plonk/Cargo.toml
- plonk/src/circuit/plonk_verifier/gadgets.rs
- plonk/src/circuit/plonk_verifier/mod.rs
- plonk/src/circuit/plonk_verifier/structs.rs
- plonk/src/constants.rs
- plonk/src/proof_system/prover.rs
- plonk/src/proof_system/snark.rs
- plonk/src/proof_system/structs.rs
- plonk/src/proof_system/verifier.rs
- plonk/src/testing_apis.rs
- plonk/src/transcript/solidity.rs
closes: #618 
Changes behavior of `SolidityTranscript`, see the linked issue for description
Question: should we also optionally append `tau` for circuits that does support lookup? currently in contract, we have to do [a useless `get_and_append_challenge` call ](https://github.com/EspressoSystems/espresso-sequencer/blob/main/contracts/src/libraries/PlonkVerifier.sol#L192-L194)for this unused challenge.
@chancharles92 @philippecamacho 
---
> refactor: use BigEndian for SolidityTranscript

- plonk/src/transcript/mod.rs
- plonk/src/transcript/solidity.rs
Part of: https://github.com/EspressoSystems/espresso-sequencer/issues/1731
- add G2 point from KZG SRS to the plonk transcript to restrict the undesirable degree of freedom
This PR is targeting a temp branch `commonprefix-patch` and would eventually be merged to main with a new tag.
---
> feat: append G2 point from SRS to transcript

- plonk/src/circuit/plonk_verifier/gadgets.rs
- plonk/src/circuit/transcript.rs
- plonk/src/constants.rs
- plonk/src/proof_system/snark.rs
- plonk/src/proof_system/verifier.rs
- plonk/src/testing_apis.rs
- plonk/src/transcript/mod.rs
- plonk/src/transcript/rescue.rs
- plonk/src/transcript/solidity.rs
- plonk/src/transcript/standard.rs
As observed in https://www.notion.so/espressosys/Fiat-Shamir-Transcript-f29ccc7a23c94178aac5cfa5d336fd63 and discussed on Zulip, we decide to remove `get_and_append_challenge()` and only use `get_challenge()` and also introduce back `state` for solidity transcript as most other projects do. 
This partially undone some changes made in https://github.com/EspressoSystems/jellyfish/pull/619.
- Updated `trait Transcript`
- change `get_and_append_challenge()` to `get_challenge()`
- add `get_n_challenges()` for multiple challenges for the same rounds
- rename `append_challenge()` to `append_field()`
- add `append_fields()`
- Updated `struct SolidityTranscript`: adding back `state` and squeeze logic (see code comment)
---
Before we can merge this PR, please make sure that all the following items …
> refactor!: refactored transcript traits and impls

- flake.nix
- plonk/src/circuit/plonk_verifier/gadgets.rs
- plonk/src/proof_system/prover.rs
- plonk/src/proof_system/verifier.rs
- relation/src/constraint_system.rs
- relation/src/gadgets/ecc/emulated/short_weierstrass.rs
closes: #655 
- [comment out grcov](https://github.com/EspressoSystems/jellyfish/commit/d2a721dc8d09e2cfaa49f30403a1e7314e22cd17)
- [clippy pacification](https://github.com/EspressoSystems/jellyfish/commit/58f1ee58d958365a2e7fc4bd67a9f88d972e18ad) for Rust 1.80
---
> fix: remove grcov from nix flake

- vid/src/advz.rs
- vid/src/advz/test.rs
closes: #659 
See commit logs. This PR removes field `Share::evals`, which breaks backward compatibility. See also https://github.com/EspressoSystems/jellyfish/issues/671#issuecomment-2321465993
---
> fix: Delete field Share::evals, extract data from eval_proofs instead

- vid/src/advz.rs
- vid/src/advz/test.rs
closes: #671 
- `Advz::evals_proof` is no longer a `Vec`
- structure of the merkle tree is changed accordingly. Each leaf in the merkle tree is a vec of polynomial evaluations as before, except now that vec looks like: https://github.com/EspressoSystems/jellyfish/blob/689555e07860c5ed6e54b467c76d9a1776f0f7b5/vid/src/advz.rs#L702-L715
- delete test `sad_path_verify_share_with_multiplicity` as it is a regression for #654 , which is no longer relevant as there is now only one merkle path in each share. 
---
> fix!: eliminate unnecessary merkle proofs in ADVZ shares

- Cargo.toml
- aead/Cargo.toml
- elgamal/Cargo.toml
- merkle_tree/Cargo.toml
- pcs/Cargo.toml
- plonk/Cargo.toml
- relation/Cargo.toml
- rescue/Cargo.toml
- signature/Cargo.toml
- utilities/Cargo.toml
- vid/CHANGELOG.md
- vid/Cargo.toml
- vrf/Cargo.toml
- bump `jf-vid` package to `0.2.0`
- update CHANGELOG for `jf-vid`. Include only nontrivial PRs relevant to jf-vid.
- See discussion below on version number vs git tags: https://github.com/EspressoSystems/jellyfish/pull/680#discussion_r1752504845
> chore: bump jf-vid version, update changelog

- merkle_tree/CHANGELOG.md
- merkle_tree/Cargo.toml
- merkle_tree/src/prelude.rs
- introduce macro rules `impl_mt_hash_256!` for implementing boilerplate for node and digest for MT that has 32 bytes output size
- impl for both Sha3 and Keccak256 under this macro
- expose a MT and lightweight MT for keccak256
@mrain do you remember why we pick rate 3 for MT? is that an assumption for our current MT internals?
---
> feat: add keccak256 merkle tree

- signature/CHANGELOG.md
- signature/Cargo.toml
- signature/src/bls_over_bls12381.rs
- signature/src/bls_over_bn254.rs
- signature/src/constants.rs
- signature/src/lib.rs
- signature/src/schnorr.rs
closes: #694 
In `jf-signature` crate
- Manually implemented `Debug` for private signing keys to not print the actual value.
- Remove derived (de)serialization. Implemented `to/from_bytes()` and the conversions to/from `TaggedBase64`.
- Private key type in `elgamal` crate still has derivations. Because of this ephemeral key in the ciphertext: https://github.com/EspressoSystems/jellyfish/blob/5f06aa175e8d49100203b027c08aa8d174e3f0d4/elgamal/src/lib.rs#L147
- Private key type in `aead` crate still has derivations. Because of this ephemeral key in the ciphertext: https://github.com/EspressoSystems/jellyfish/blob/5f06aa175e8d49100203b027c08aa8d174e3f0d4/aead/src/lib.rs#L279
- `jf-vrf` crate should be updated after to adopt these changes in `jf-signature`.
---
Before we can merge this PR, …
> chore: remove derived `Debug` and `Serialize` from private key types

- .gitignore
- Cargo.toml
- merkle_tree/Cargo.toml
- merkle_tree/src/hasher.rs
- merkle_tree/src/prelude.rs
- poseidon2/CHANGELOG.md
- poseidon2/Cargo.toml
- poseidon2/benches/p2_native.rs
- poseidon2/src/constants.rs
- poseidon2/src/constants/bls12_381.rs
- poseidon2/src/constants/bn254.rs
- poseidon2/src/external.rs
- poseidon2/src/internal.rs
- poseidon2/src/lib.rs
closes: #704 
When we merge, I'd like to merge with commits (leave intermediate steps in the git history) if possible, as I try to make each commit self-contained in scope. 
- Add `struct Poseidon2` and its permutation `::permute()` and `permute_mut()`
- Add `trait Poseidon2Params` whose generic parameter is much cleaner than plonky3, while sufficient for our purposes
- Add concrete parameters (2 instances for Bls12-381, 1 instance for Bn254) in `poseidon2/constants/` and add test vectors (generated by reference impl by `zkhash`)
- Implement `HasherAlgorithm` for `Poseidon2` so that it can be used in Merkle tree as the hash function candidate
---
checked off. If any of the checklist items are not …
> feat: Poseidon2 implementation and availabe as Merkle Hash

- Cargo.toml
- elgamal/Cargo.toml
- merkle_tree/Cargo.toml
- plonk/src/proof_system/structs.rs
- poseidon2/Cargo.toml
- poseidon2/src/constants.rs
- poseidon2/src/lib.rs
- poseidon2/src/sponge.rs
- signature/Cargo.toml
- vid/Cargo.toml
- vrf/Cargo.toml
Part of: #709 (Item 1 and 3)
- Implement a generic P2-based Sponge struct which implements `nimue`'s `trait Sponge`
- Concretely instantiate `DuplexSponge` for all the parameters we have (including various rate, given the same state size)
- Add tests for all (both functional correctness as sponge used in transcript, and a naive statistical tests that output of these sponge-squeezed bytes are close to uniform distribution)
`nimue-v0.1.0` which is the only published version, has compilation error, which I have reported upstream and help submit a PR to fix it. 
I will push for a release tag of `0.1.1` from the upstream and later repin our `nimue` dependency, for now, I'm pointing to my own fork/branch
--- …
> feat: Poseidon2-based Sponge function

- merkle_tree/CHANGELOG.md
- merkle_tree/Cargo.toml
New release for `jf-merkle-tree` to `0.2.1`
---
> chore: bump jf-merkle-tree to 0.2.1

- Cargo.toml
- poseidon2/benches/p2_native.rs
- poseidon2/src/external.rs
- poseidon2/src/internal.rs
- poseidon2/src/lib.rs
closes: #738 
- Unroll `.pow(5)` to significantly cut down permutation cost
Download this: [cargo 2025-01-14 16.20 profile.json](https://github.com/user-attachments/files/18407649/cargo.2025-01-14.16.20.profile.json)
Go to `https://profiler.firefox.com` and load this file (which you can hover around to see the percentage clearly). Alternatively, see the below screenshot: 
~~Right now, the new dominant cost leader is `MulAssign` which I don't think we can cut further, but I still didn't quite achieve the same performance than the paper reported, still a (7.2-6.5) gap for bls12, with t=2.~~
---
> perf: improve poseidon2 time by 2 times

- merkle_tree/Cargo.toml
- merkle_tree/src/prelude.rs
- poseidon2/src/crhf.rs
- poseidon2/src/external.rs
- poseidon2/src/sponge.rs
closes: #XXXX
> In FixedLenPoseidon2Hash and VariableLenPoseidon2Hash, the documentation misleadingly states that this sponge-based CRHF uses the Poseidon2 permutation. However, there is nothing about these structs that require use of the Poseidon2 permutation. It will use the Poseidon2 permutation only if it is parameterized by a Poseidon2 Sponge S.
Fix the above issue, caught external review
Not yet release the next tag, so okay to use a non-pinned dependency
---
> chore: restrict poseidon sponge for p2-based hash

- merkle_tree/benches/merkle_path.rs
- merkle_tree/src/append_only.rs
- merkle_tree/src/hasher.rs
- merkle_tree/src/internal.rs
- merkle_tree/src/lib.rs
- merkle_tree/src/light_weight.rs
- merkle_tree/src/macros.rs
- merkle_tree/src/namespaced_merkle_tree/mod.rs
- merkle_tree/src/namespaced_merkle_tree/proof.rs
- merkle_tree/src/universal_merkle_tree.rs
- merkle_tree/tests/merkle_tree_hasher.rs
- merkle_tree/tests/proptest_merkle.rs
- vid/src/advz.rs
Closes: #805 
- update the `MerkleTreeScheme` trait so that the `.verify()` function accept the commitment instead of digest root node, and we check the proof length against the `commitment.height()` to prevent extension 
- update the implementation and unit tests to use the new api
- update `vid` crate to use the new api
---
> refactor!: merkle proof verify accept commitment instead of digest node
