CHANGELOG.md, README.md, utilities/Cargo.toml
Updated URL from SpectrumXYZ to EspressoSystems to reflect the recent name change
---
- not relevant
- not relevant
- not relevant
=> Updated URL from SpectrumXYZ to EspressoSystems

plonk/Cargo.toml, primitives/Cargo.toml, rescue/Cargo.toml, utilities/Cargo.toml, utilities_derive/Cargo.toml
Preparing a release for Seahorse to pin to.  This just updates the cargo.toml to match what I plan to tag as the release.
---
=> Release 0.1.1

plonk/src/errors.rs
Refactor the error message of `SnarkError(WrongQuotientPolyDegree(127, 87))` to help developer better debug. 
Related issue: #92
=> refactor error msg

plonk/src/circuit/customized/ecc/mod.rs, plonk/src/circuit/customized/ultraplonk/mod_arith.rs, plonk/src/proof_system/structs.rs, primitives/src/signatures/schnorr.rs, rescue/src/errors.rs, rescue/src/lib.rs
=> Fixed clippy build error problem

plonk/src/circuit/plonk_verifier/gadgets.rs, plonk/src/circuit/plonk_verifier/mod.rs, plonk/src/circuit/plonk_verifier/poly.rs, plonk/src/proof_system/prover.rs, primitives/src/circuit/rescue/native.rs, primitives/src/circuit/rescue/non_native.rs, primitives/src/signatures/mod.rs, primitives/src/vrf/blsvrf.rs, relation/src/constraint_system.rs, relation/src/gadgets/arithmetic.rs, relation/src/gadgets/ultraplonk/mod_arith.rs, relation/src/gadgets/ultraplonk/non_native_gates.rs
Fixed clippy errors & warnings due to CI upgrade to rust 1.65.0.
=> Fixed clippy errors & warnings.

CHANGELOG.md, primitives/Cargo.toml
Following the new draft standard we propose: 
https://www.notion.so/espressosys/Jellyfish-Release-Guide-4ed9122ec5bd49fe8d63f1baa6811d1a
---
=> improve CHANGELOG to our new standard

.github/workflows/build.yml, .github/workflows/periodic_checks.yml, flake.nix, plonk/Cargo.toml, plonk/src/testing_apis.rs, plonk/src/transcript/rescue.rs, primitives/Cargo.toml, relation/Cargo.toml, utilities/Cargo.toml
Related to https://github.com/EspressoSystems/jellyfish/issues/127, but not closing it yet.
This is just an easy win since `cargo-udeps` might still leave some unused deps undetected. At some point I'll review them one-by-one.
---
=> Clean up deps

CHANGELOG.md
For PR https://github.com/EspressoSystems/jellyfish/pull/158
---
=> Add missing changelog for MerkleTreeGadget refactor

CHANGELOG.md, primitives/src/merkle_tree/internal.rs, primitives/src/merkle_tree/light_weight.rs, primitives/src/merkle_tree/macros.rs, primitives/src/merkle_tree/mod.rs, primitives/src/merkle_tree/prelude.rs, primitives/src/merkle_tree/universal_merkle_tree.rs
closes: #141 
Gadget implementation not required.
---
=> Light weight merkle tree implementation.

README.md
A hello-world PR to clarify nix and direnv install instructions in `README.md`.
- "git hooks" section: is this necessary? Perhaps it should be moved to a later point in the doc so as to avoid cluttering the basic instructions 
---
=> doc: tidy nix, direnv install instructions

primitives/src/circuit/merkle_tree/mod.rs, primitives/src/circuit/merkle_tree/rescue_merkle_tree.rs, primitives/src/circuit/merkle_tree/sparse_merkle_tree.rs, primitives/src/merkle_tree/prelude.rs, primitives/src/merkle_tree/universal_merkle_tree.rs
=> Non-membership proof for SMT

CHANGELOG.md, Cargo.toml, primitives/Cargo.toml
a new version bump with more stabilized APIs and more (see CHANGELOG for the concrete list)
---
=> Release 0.2.0

plonk/src/proof_system/structs.rs, primitives/Cargo.toml
=> fix clippy error

plonk/Cargo.toml, primitives/Cargo.toml, utilities/Cargo.toml
closes: #XXXX
Link tagged-base64 deps to the right place. Need to re-tag the repo.
---
=> update tagged-base64 deps

primitives/src/pcs/mod.rs, primitives/src/pcs/multilinear_kzg/mod.rs, primitives/src/pcs/multilinear_kzg/srs.rs, primitives/src/pcs/univariate_kzg/mod.rs, primitives/src/pcs/univariate_kzg/srs.rs
Small API change. Tests pass. Is anyone aware of downstream usage of `PolynomialCommitmentScheme` that might break?
closes: #228 
---
=> Remove generic parameter from PCS trait

primitives/src/erasure_code/mod.rs, primitives/src/erasure_code/reed_solomon_erasure.rs
closes: #235 
This is not a priority but it's Friday night and I'm having fun so I did it anyway. 😛 
No change in functionality. Successful use of new API here https://github.com/EspressoSystems/hotshot-primitives/blob/97e2fe3c955b233e9c622c258f2570ab220b3790/src/vid/advz.rs#L207-L210
---
=> Accept IntoIterator args to save memory

primitives/src/circuit/merkle_tree/rescue_merkle_tree.rs, utilities/src/conversion.rs
closes: #239
With a strengthened unit test.
---
=> Fix bug in merkle tree gadget

primitives/src/pcs/structs.rs
closes: #246 
After some trial-and-error (see commit history if you're curious) I found that the combination of `From` and `AsRef` works well.
---
=> Impl conversion traits for PCS `Commitment`

utilities/src/conversion.rs
Address old PR comments:
- https://github.com/EspressoSystems/jellyfish/pull/250#discussion_r1180436672
- https://github.com/EspressoSystems/jellyfish/pull/234#discussion_r1180439485
- https://github.com/EspressoSystems/jellyfish/pull/234#discussion_r1180419419
---
=> chore: bytes-from-field cleanup

.github/workflows/build.yml, .github/workflows/periodic_checks.yml, README.md, plonk/Cargo.toml
Fixing periodic check on unused dep in CI: https://github.com/EspressoSystems/jellyfish/actions/runs/4969545780
=> fix cargo udeps failure in ci

primitives/Cargo.toml, primitives/src/merkle_tree/hasher.rs, primitives/src/merkle_tree/mod.rs, primitives/tests/merkle_tree_hasher.rs
=> feat: HasherMerkleTree convenience wrapper for Digest-compatible hashers

primitives/benches/merkle_path.rs, primitives/src/merkle_tree/append_only.rs, primitives/src/merkle_tree/hasher.rs, primitives/src/merkle_tree/light_weight.rs, primitives/src/merkle_tree/macros.rs, primitives/src/merkle_tree/mod.rs, primitives/src/merkle_tree/universal_merkle_tree.rs, primitives/tests/merkle_tree_hasher.rs
=> fix!: restore pos arg to MerkleTreeScheme::verify

Cargo.toml
This is pre-release for early feedback on `v0.4.0` later. 
---
=> Release: pre-release 0.4.0-pre.0

CHANGELOG.md, plonk/src/circuit/plonk_verifier/gadgets.rs, plonk/src/circuit/plonk_verifier/mod.rs, primitives/benches/merkle_path.rs, primitives/src/circuit/elgamal.rs, primitives/src/pcs/multilinear_kzg/util.rs, primitives/src/pcs/poly.rs, primitives/src/pcs/univariate_kzg/mod.rs, primitives/src/toeplitz.rs, primitives/tests/merkle_tree_hasher.rs, relation/Cargo.toml, relation/src/gadgets/arithmetic.rs, relation/src/gadgets/ecc/mod.rs, relation/src/gadgets/ecc/non_native.rs, relation/src/gadgets/emulated.rs, relation/src/gadgets/mod.rs, relation/src/gates/arithmetic.rs, scripts/run_tests.sh
=> Non-native field operations with ECC addition

primitives/src/merkle_tree/examples.rs, primitives/src/merkle_tree/mod.rs, primitives/src/merkle_tree/namespaced_merkle_tree.rs, primitives/src/merkle_tree/universal_merkle_tree.rs
Introduces the NMT trait and a namespaced hasher
Close https://github.com/EspressoSystems/espresso-sequencer/issues/365
=> NMT trait and hash function integration

CHANGELOG.md, primitives/src/merkle_tree/examples.rs, primitives/src/merkle_tree/hasher.rs, primitives/src/merkle_tree/internal.rs, primitives/src/merkle_tree/macros.rs, primitives/src/merkle_tree/mod.rs, primitives/src/merkle_tree/namespaced_merkle_tree.rs, primitives/src/merkle_tree/prelude.rs, primitives/src/merkle_tree/universal_merkle_tree.rs
closes: #275
`DigestAlgorithm` now returns a `Result` type.
---
=> DigestAlgorithm API small refactor

relation/src/gadgets/emulated.rs
=> [BUG FIXES] Corrected range_check parameter in emulated field operations

primitives/src/aead.rs
I removed the CanonicalSerde in #270, but now I need to add it back realizing that the downstream need (`jf-cap`), the source of the problem is documented in https://github.com/EspressoSystems/jellyfish/issues/288#issuecomment-1582569179
---
=> chore: add back canonical_serde for aead structs

.github/workflows/build.yml
We should build all Pull Requests, not just ones targetting main
=> Make all PRs build

primitives/src/merkle_tree/namespaced_merkle_tree/hash.rs, primitives/src/merkle_tree/namespaced_merkle_tree/mod.rs, primitives/src/merkle_tree/namespaced_merkle_tree/proof.rs
Cleans up the NMT module by splitting it into `mod.rs`, `proof.rs`, `hash.rs`.
---
- [ x] Targeted PR against correct branch (main)
- [x ] Linked to GitHub issue with discussion and accepted design OR have an explanation in the PR that describes this work.
=> feat: Reorganize NMT repo

primitives/src/circuit/merkle_tree/mod.rs, primitives/src/merkle_tree/append_only.rs, primitives/src/merkle_tree/examples.rs, primitives/src/merkle_tree/hasher.rs, primitives/src/merkle_tree/internal.rs, primitives/src/merkle_tree/light_weight.rs, primitives/src/merkle_tree/macros.rs, primitives/src/merkle_tree/mod.rs, primitives/src/merkle_tree/namespaced_merkle_tree/hash.rs, primitives/src/merkle_tree/namespaced_merkle_tree/mod.rs, primitives/src/merkle_tree/universal_merkle_tree.rs, primitives/tests/merkle_tree_hasher.rs
Added some derived traits for integration purposes, and allow the MerkleTree to return leaves by reference so that the NMT can return a leaf iterator. 
---
=> feat: Trait-related tweaks for NMT integration

primitives/Cargo.toml, primitives/src/circuit/rescue/native.rs, primitives/src/rescue/rescue_constants/bls12_377_base.rs, primitives/src/rescue/rescue_constants/ed_on_bls12_377_base.rs, primitives/src/rescue/rescue_constants/ed_on_bls12_381_base.rs, primitives/src/rescue/rescue_constants/ed_on_bn254_base.rs
avoids the compiling error
Should fix the compiling error due to the update of `curve25519-dalek`. 
---
=> fix: update dependency for crypto_kx to avoid compiling error

relation/src/gadgets/ecc/emulated/short_weierstrass.rs, relation/src/gadgets/ecc/mod.rs, relation/src/gadgets/emulated.rs
Implements `Default` For `TEPoint` and `SWPoint`. For snarked qc.
---
=> feat: impl Default for ECC Points

.github/workflows/commit-title.yaml, primitives/src/signatures/bls_over_bn254.rs, primitives/src/signatures/mod.rs
This is for support of https://github.com/EspressoSystems/hotshot-primitives/pull/66
=> chore: minor trait bound update

primitives/src/merkle_tree/namespaced_merkle_tree/mod.rs
here: https://github.com/EspressoSystems/jellyfish/actions/runs/5716373114/job/15487763347
---
=> fix: addressed CI error

primitives/Cargo.toml
closes: #363 
```bash
$ cargo update
$ cargo tree | grep curve25519                                                                                                                                                  [20:49:29]
│   │   ├── curve25519-dalek v4.0.0
```
---
=> chore(deps): bump `crypto_kx` to 0.2.1

primitives/src/pcs/univariate_kzg/mod.rs, primitives/src/vid/advz.rs, primitives/src/vid/advz/payload_prover.rs, primitives/src/vid/payload_prover.rs
=> chore: remove excess generality in ADVZ

flake.lock, primitives/src/vid/advz.rs
=> fix: ADVZ Share serde derivation

plonk/src/proof_system/prover.rs, primitives/src/merkle_tree/hasher.rs, primitives/src/vid/advz/payload_prover.rs, primitives/src/vid/payload_prover.rs
=> fix: Add trait bounds to proof types

primitives/src/vid/advz/payload_prover.rs
=> fix: ADVZ payload prover panic on some payload byte lengths

primitives/src/signatures/schnorr.rs
closes: #XXXX
Change the return type, so that one could extract a signing key out of a schnorr key pair.
---
=> chore: a better interface for schnorr signature key pair

primitives/src/circuit/merkle_tree/mod.rs, primitives/src/circuit/rescue/non_native.rs, primitives/src/merkle_tree/mod.rs, primitives/src/pcs/poly.rs
Minor typo fix of comments. I don't think a changelog entry is necessary. 
---
=> chore(primitives/src): typo fix 

primitives/src/merkle_tree/examples.rs, primitives/src/merkle_tree/namespaced_merkle_tree/hash.rs, primitives/src/merkle_tree/namespaced_merkle_tree/mod.rs, primitives/src/merkle_tree/prelude.rs, primitives/src/signatures/mod.rs, relation/src/gadgets/mod.rs, utilities/src/lib.rs
Small fixes, nothing to close.
Signature public parameters should be Clonable.
Exporting Sha3Digest to instantiate merkle tree.
---
=> chore: miscellaneous fixes requested.

primitives/src/signatures/bls_over_bn254.rs
=> chore: expose `SignKey::generate()` in `bls_over_bn254`

CHANGELOG.md, plonk/src/circuit/plonk_verifier/gadgets.rs, plonk/src/circuit/plonk_verifier/mod.rs, plonk/src/circuit/plonk_verifier/poly.rs, plonk/src/proof_system/snark.rs, plonk/src/proof_system/structs.rs, primitives/src/circuit/signature/schnorr.rs, primitives/src/pcs/multilinear_kzg/batching.rs, primitives/src/pcs/multilinear_kzg/mod.rs, primitives/src/pcs/multilinear_kzg/srs.rs, primitives/src/pcs/univariate_kzg/mod.rs, primitives/src/signatures/schnorr.rs, primitives/src/toeplitz.rs, primitives/src/vid/advz.rs, relation/src/gadgets/arithmetic.rs, relation/src/gadgets/ecc/glv.rs, relation/src/gadgets/ecc/mod.rs, relation/src/gadgets/ecc/msm.rs, relation/src/gadgets/ultraplonk/mod_arith.rs, relation/src/gadgets/ultraplonk/non_native_gates.rs, utilities/src/conversion.rs, utilities/src/lib.rs, utilities/src/multi_pairing.rs
=> chore: update CHANGELOG for new tag release

primitives/src/merkle_tree/mod.rs
=> docs: add example to `update_with` documentation.

CHANGELOG.md, primitives/Cargo.toml, primitives/src/circuit/merkle_tree/mod.rs, primitives/src/merkle_tree/append_only.rs, primitives/src/merkle_tree/internal.rs, primitives/src/merkle_tree/light_weight.rs, primitives/src/merkle_tree/macros.rs, primitives/src/merkle_tree/mod.rs, primitives/src/merkle_tree/universal_merkle_tree.rs
- Introduce `NonDestructiveUniversalMerkleTreeScheme` trait.
- Refactor internal wrapper of `MerkleNode` from `Box` to `Arc`.
- Add persistent update functionalities to `UniversalMerkleTree`.
---
=> feat: implement non destructive universal Merkle tree

primitives/src/signatures/bls_over_bn254.rs, primitives/src/signatures/schnorr.rs
=> chore: allow signature key pairs to be generated from a sign key

.github/workflows/build.yml, .typos.toml, CHANGELOG.md, README.md, bench.md, flake.nix, plonk/src/circuit/plonk_verifier/poly.rs, plonk/src/circuit/plonk_verifier/structs.rs, plonk/src/proof_system/prover.rs, plonk/src/proof_system/structs.rs, plonk/src/proof_system/verifier.rs, primitives/src/circuit/merkle_tree/mod.rs, primitives/src/errors.rs, primitives/src/lib.rs, primitives/src/merkle_tree/internal.rs, primitives/src/merkle_tree/mod.rs, primitives/src/pcs/mod.rs, primitives/src/pcs/poly.rs, primitives/src/pcs/univariate_kzg/mod.rs, primitives/src/vid/advz.rs, primitives/src/vid/advz/bytes_to_field.rs, relation/src/constraint_system.rs, relation/src/gadgets/ecc/mod.rs, relation/src/gadgets/emulated.rs, relation/src/gadgets/range.rs, utilities/src/conversion.rs
Add spell check in CI and pre-commit.
---
=> chore: spell check

primitives/src/lib.rs, primitives/src/pcs/univariate_kzg/mod.rs, primitives/src/vid/advz.rs, primitives/src/vid/advz/payload_prover.rs, primitives/src/vid/advz/precomputable.rs
=> chore: leftover works for GPU VID

Cargo.toml, plonk/Cargo.toml, primitives/Cargo.toml, primitives/src/circuit/merkle_tree/mod.rs, primitives/src/circuit/merkle_tree/universal_merkle_tree.rs, primitives/src/merkle_tree/append_only.rs, primitives/src/merkle_tree/examples.rs, primitives/src/merkle_tree/hasher.rs, primitives/src/merkle_tree/internal.rs, primitives/src/merkle_tree/light_weight.rs, primitives/src/merkle_tree/macros.rs, primitives/src/merkle_tree/mod.rs, primitives/src/merkle_tree/namespaced_merkle_tree/mod.rs, primitives/src/merkle_tree/namespaced_merkle_tree/proof.rs, primitives/src/merkle_tree/prelude.rs, primitives/src/merkle_tree/universal_merkle_tree.rs, primitives/src/vid/advz.rs, relation/Cargo.toml, utilities/Cargo.toml
- cleanup and re-organize dependencies
- use const generics instead of `typenum` 
Remaining problem:
- still cannot pass no_std check here: `./scripts/check_no_std.sh`
---
=> chore: cleanup dependencies

plonk/src/constants.rs, plonk/src/transcript/solidity.rs
Related to https://github.com/EspressoSystems/espresso-sequencer/issues/1006.
Simplify the solidity transcript computation in order to save gas in the light client contract.
---
=> fix: optimize solidity transcript

pcs/Cargo.toml, pcs/src/lib.rs, vid/src/advz.rs
closes: #XXXX
Fix the compilation failure for `jf-pcs` and `jf-vid` when `gpu-vid` feature is on.
Tested locally that we can run the `disperse_timer()`.
---
=> fix(pcs): compilation fix for jf-pcs&jf-vid

elgamal/Cargo.toml, merkle_tree/Cargo.toml, plonk/Cargo.toml, rescue/Cargo.toml, signature/Cargo.toml, vrf/Cargo.toml
Originally if your crate depends on `jf-signature` and `jf-relation`, you cannot turn on `jf-relation/parallel` because `jf-signature` depends on `jf-relation` without `parallel` feature.
Propagate the `parallel` feature flag so that upstream crate won't have compilation issue.
---
=> fix: parallel feature flags

vrf/CHANGELOG.md, vrf/Cargo.toml, vrf/src/lib.rs
closes: #XXXX
Upgrade `jf-signature` dependency to 0.2.0.
- Secret keys are not required to be serde Serializable.
---
=> chore(deps): upgrade dependency for `jf-vrf`

.github/workflows/build.yml, scripts/run_benchmarks.m4, scripts/run_tests.sh, scripts/test_coverage.sh
closes: #XXXX
`cargo +nightly check -p jf-pcs` runs forever on cargo nightly version >1.84.0
Pin to rust nightly toolchain `nightly-2024-06-25`
---
=> chore: pin the nightly toolchain

merkle_tree/src/examples.rs, merkle_tree/src/gadgets/mod.rs, merkle_tree/src/hasher.rs, merkle_tree/src/lib.rs, merkle_tree/src/prelude.rs, merkle_tree/src/universal_merkle_tree.rs, relation/src/gadgets/ecc/mod.rs
=> fix(merkle-tree): add domain separation for merkle tree hash

merkle_tree/src/prelude.rs
=> fix(merkle-tree): correct domain separator

signature/CHANGELOG.md, signature/src/bls_over_bls12381.rs, signature/src/bls_over_bn254.rs, signature/src/lib.rs
=> fix: validity test for BLS over BN

merkle_tree/CHANGELOG.md, merkle_tree/Cargo.toml, merkle_tree/src/internal.rs, merkle_tree/src/prelude.rs
=> fix: range checks for merkle tree

signature/CHANGELOG.md, signature/Cargo.toml
=> chore(deps): make `jf-rescue` optional for `jf-signature`
